[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ICOW = "3f0c05cb-d2a1-4c03-b976-c0e1c11e0dd4"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimOptDecisions = "8764eb7a-9599-4112-a7c7-9b4115e89f97"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
